accounts/urls.py
from django.urls import path
from . import cbviews as views
from .views import csv_report

app_name = 'accounts'

urlpatterns = [
    path('', views.UserList.as_view(), name='list'),
    path('<str:username>', views.UserDetail.as_view(), name='detail'),
    path('add/', views.AddUser.as_view(), name='add'),
    path('edit/<str:username>', views.EditUser.as_view(), name='edit'),
    path('delete/<str:username>', views.DeleteUser.as_view(), name='delete'),
    path('report/', csv_report, name="report"),
]

milo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect

urlpatterns = [
    path('', lambda request: redirect('accounts:list')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.shortcuts import reverse
from random import randint


class User(AbstractUser):
    birthday = models.DateField(null=True)
    number = models.PositiveSmallIntegerField(editable=False, blank=False, null=True)

    def get_absolute_url(self):
        return reverse('accounts:detail', kwargs={'username': self.username})

    def save(self, *args, **kwargs):
        if not self.number:
            self.number = randint(1, 100)
        super().save(*args, **kwargs)

accounts/forms.py
from django.forms import ModelForm, TextInput
from .models import User

class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name',
                  'email', 'birthday']
        widgets = {
            'birthday': TextInput(attrs={'autocomplete': 'off'})
        }

accounts/views.py
from django.http import HttpResponse
from .templatetags.accounts_tags import is_allowed, bizzfuzz
from .models import User
import csv


def csv_report(request):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="report.csv"'

    writer = csv.writer(response)
    writer.writerow(['Username', 'Birthday', 'Eligible', 'Random Number', 'BizzFuzz'])
    for user in User.objects.all():
        writer.writerow([
            user.username, 
            user.birthday,
            is_allowed(user),
            user.number,
            bizzfuzz(user.number)
        ])
    return response

accounts/templates/accounts/add_user.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Add User{% endblock %}

{% block content %}
<h1>Add new user:</h1>
<form method="post" action=".">
    <table class="user-info">
        <tr>
            {{ form.username.errors}}
            <td>{{ form.username.label }}</td>
            <td>{{ form.username }}</td>
        </tr>
        <tr>
            <td>{{ form.first_name.label}}</td>
            <td>{{ form.first_name }}</td>
        </tr>
        <tr>
            <td>{{ form.last_name.label }}</td>
            <td>{{ form.last_name }}</td>
        </tr>
        <tr>
            {{ form.email.errors}}
            <td>Email</td>
            <td>{{ form.email }}</td>
        </tr>
        <tr>
            {{ form.birthday.errors}}
            <td>{{ form.birthday.label}}</td>
            <td>{{ form.birthday }}</td>
        </tr>
    </table>
    {% csrf_token %}
    <button type="submit" id="save">Add</button>
</form>
<link rel="stylesheet" href="{% static 'jquery-ui/jquery-ui.min.css' %}">
<script src="{% static 'jquery-ui/external/jquery/jquery.js' %}"></script>
<script src="{% static 'jquery-ui/jquery-ui.min.js' %}"></script>
<script>$("#id_birthday").datepicker({changeYear: true, yearRange: "-150:+0"});</script>
{% endblock %}

accounts/templates/accounts/delete_user.html
{% extends 'base.html' %}
{% block title %}Delete User{% endblock %}

{% block content %}
<h1>Are you sure you want to delete "{{ object }}"?</h1>
<form method="post">
   
    <a href="{% url 'accounts:detail' object.username %}">
        <button type="button" id="edit" class="post-form">Go back</button>
    </a>
    <button type="submit" id="delete">Confirm</button>
    {% csrf_token %}
</form>
{% endblock %}

accounts/templates/accounts/detail.html
{% extends 'base.html' %}
{% load accounts_tags %}
{% block title %}User Info{% endblock %}

{% block content %}
<h1>{{ user.username }}</h1>

<table class="user-info">
    <tr>
        <td>First name</td>
        <td><strong>{{ user.first_name }}</strong></td>
    </tr>
    <tr>
        <td>Last name</td>
        <td><strong>{{ user.last_name }}</strong></td>
    </tr>
    <tr>
        <td>Email</td>
        <td><strong>{{ user.email }}</strong></td>
    </tr>
    <tr>
        <td>Birthday</td>
        <td><strong>{{ user.birthday }}</strong></td>
    </tr>
    <tr>
        <td>Status</td>
        <td><strong class="status">{% is_allowed user %}</strong></td>
    </tr>
    <tr>
        <td>Number</td>
        <td><strong>{{ user.number }}</strong></td>
    </tr>
    <tr>
        <td>BizzFuzz</td>
        <td><strong>{% bizzfuzz user.number %}</strong></td>
    </tr>
</table>

<a href="{% url 'accounts:edit' user.username %}">
    <button id="edit">Edit</button>
</a>
<a href="{% url 'accounts:delete' user.username %}">
    <button id="delete">Delete</button>
</a>
{% endblock %}

accounts/templates/accounts/edit_user.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Edit User{% endblock %}

{% block content %}
<h1>Edit user data:</h1>
<form method="post">
    <table class="user-info">
        <tr>
            {{ form.username.errors}}
            <td>{{ form.username.label }}</td>
            <td><strong>{{ form.username }}</strong></td>
        </tr>
        <tr>
            <td>{{ form.first_name.label}}</td>
            <td>{{ form.first_name }}</td>
        </tr>
        <tr>
            <td>{{ form.last_name.label }}</td>
            <td>{{ form.last_name }}</td>
        </tr>
        <tr>
            {{ form.email.errors}}
            <td>Email</td>
            <td>{{ form.email }}</td>
        </tr>
        <tr>
            {{ form.birthday.errors}}
            <td>{{ form.birthday.label}}</td>
            <td>{{ form.birthday }}</td>
        </tr>
    </table>
    {% csrf_token %}
    <a href="{% url 'accounts:detail' object.username %}">
        <button type="button" id="edit" class="post-form">Go back</button>
    </a>
    <button id="save" type="submit">Save</button>
</form>
<link rel="stylesheet" href="{% static 'jquery-ui/jquery-ui.min.css' %}">
<script src="{% static 'jquery-ui/external/jquery/jquery.js' %}"></script>
<script src="{% static 'jquery-ui/jquery-ui.min.js' %}"></script>
<script>$("#id_birthday").datepicker();</script>
{% endblock %}

accounts/templates/accounts/list.html
{% extends 'base.html' %}
{% load accounts_tags %}
{% block title %}User List{% endblock %}

{% block content %}
<h1>User List</h1>
<a id="report" href="{% url 'accounts:report' %}" >Download report</a>
<table class="user-list">
    <thead>
        <td>Username</td>
        <td>First name</td>
        <td>Last name</td>
        <td>Birthday</td>
        <td>Status</td>
        <td>Number</td>
        <td>BizzFuzz</td>
    </thead>
    {% for user in users %}
        <tr>
            <td>
                <h3 class="username" ><a href="{% url 'accounts:detail' user.username %}">{{ user.username }}</a></h3>
            </td>
            <td>{{ user.first_name }}</td>
            <td>{{ user.last_name }}</td>
            <td>{{ user.birthday }}</td>
            <td><strong class="status">{% is_allowed user %}</strong></td>
            <td>{{ user.number }}</td>
            <td>{% bizzfuzz user.number %}</td>  
        </tr>
    {% empty %}
        <tr><td class="empty">No users</td></tr>
    {% endfor %}
<table>

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}
    
        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
        </span>
    
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock %}

common/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Milo Test{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
</head>
<body>
    <nav class="navbar">
        <a class="navbar-item" href="{% url 'accounts:list' %}">Users</a>
        <a class="navbar-item" href="{% url 'accounts:add' %}">Add new user</a>
    </nav>

    <div class="container">
        {% block content %}
        {% endblock %}
    </div>    
    
    <script type="text/javascript" src="{% static 'js/main.js' %}"></script>
</body>
</html>